### PR TITLE
Allow for files with no concentrations

### LINKED ISSUE #81: The syntax does not permit for a CRN with no concentrations
It will crash if there are no initial concentrations in the CRN, and the error message will not be helpful either. 

But since reactions of the form `0 -> c` are possible, CRNs with no concentrations at all should be possible to define too.

### PR DESCRIPTION
**Pull request by RasmusRendal**
This should close #81

### CODE REVIEW

**Comment by adramaxxx** [comment]
er reaktionen 0 -> c også lovlig, såfremt c ikke er declared?

**Comment by RasmusRendal** [comment]
Declaring species is not something that is done in crnsimul. Here, we can infer that if a specie is mentioned anywhere, it is meant to be part of the reaction network.

**Comment by adramaxxx** [comment]
but, since it is a part of the reaction network, should it not have a starting concentration?

**Comment by RasmusRendal** [comment]
Crnsimul has always handled that as the start concentration implicitly being zero.

**Review by adramaxxx — APPROVED** [review]

**Pull request merged**
